# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_pb2 as device__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AcquisitionDeviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/xiaoche.device.AcquisitionDevice/ListDevices',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.ListDevicesReply.FromString,
                _registered_method=True)
        self.OpenDevice = channel.unary_unary(
                '/xiaoche.device.AcquisitionDevice/OpenDevice',
                request_serializer=device__pb2.OpenDeviceRequest.SerializeToString,
                response_deserializer=device__pb2.CommandReply.FromString,
                _registered_method=True)
        self.CloseDevice = channel.unary_unary(
                '/xiaoche.device.AcquisitionDevice/CloseDevice',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.CommandReply.FromString,
                _registered_method=True)
        self.StartSampling = channel.unary_unary(
                '/xiaoche.device.AcquisitionDevice/StartSampling',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.CommandReply.FromString,
                _registered_method=True)
        self.StopSampling = channel.unary_unary(
                '/xiaoche.device.AcquisitionDevice/StopSampling',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.CommandReply.FromString,
                _registered_method=True)
        self.ResetDevice = channel.unary_unary(
                '/xiaoche.device.AcquisitionDevice/ResetDevice',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.CommandReply.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/xiaoche.device.AcquisitionDevice/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.StatusReply.FromString,
                _registered_method=True)
        self.SubscribeProcessedFrames = channel.unary_stream(
                '/xiaoche.device.AcquisitionDevice/SubscribeProcessedFrames',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=device__pb2.ProcessedFrameReply.FromString,
                _registered_method=True)


class AcquisitionDeviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartSampling(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopSampling(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeProcessedFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AcquisitionDeviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=device__pb2.ListDevicesReply.SerializeToString,
            ),
            'OpenDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDevice,
                    request_deserializer=device__pb2.OpenDeviceRequest.FromString,
                    response_serializer=device__pb2.CommandReply.SerializeToString,
            ),
            'CloseDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseDevice,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=device__pb2.CommandReply.SerializeToString,
            ),
            'StartSampling': grpc.unary_unary_rpc_method_handler(
                    servicer.StartSampling,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=device__pb2.CommandReply.SerializeToString,
            ),
            'StopSampling': grpc.unary_unary_rpc_method_handler(
                    servicer.StopSampling,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=device__pb2.CommandReply.SerializeToString,
            ),
            'ResetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetDevice,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=device__pb2.CommandReply.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=device__pb2.StatusReply.SerializeToString,
            ),
            'SubscribeProcessedFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeProcessedFrames,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=device__pb2.ProcessedFrameReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'xiaoche.device.AcquisitionDevice', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('xiaoche.device.AcquisitionDevice', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AcquisitionDevice(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoche.device.AcquisitionDevice/ListDevices',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            device__pb2.ListDevicesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoche.device.AcquisitionDevice/OpenDevice',
            device__pb2.OpenDeviceRequest.SerializeToString,
            device__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoche.device.AcquisitionDevice/CloseDevice',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            device__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartSampling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoche.device.AcquisitionDevice/StartSampling',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            device__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopSampling(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoche.device.AcquisitionDevice/StopSampling',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            device__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoche.device.AcquisitionDevice/ResetDevice',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            device__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/xiaoche.device.AcquisitionDevice/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            device__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeProcessedFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/xiaoche.device.AcquisitionDevice/SubscribeProcessedFrames',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            device__pb2.ProcessedFrameReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
