# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import multifreq_eddy_pb2 as multifreq__eddy__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in multifreq_eddy_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MultiFreqEddyCurrentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/multifreqeddy.MultiFreqEddyCurrent/ListDevices',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=multifreq__eddy__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.StartDetection = channel.unary_unary(
                '/multifreqeddy.MultiFreqEddyCurrent/StartDetection',
                request_serializer=multifreq__eddy__pb2.StartDetectionRequest.SerializeToString,
                response_deserializer=multifreq__eddy__pb2.OperationReply.FromString,
                _registered_method=True)
        self.StopDetection = channel.unary_unary(
                '/multifreqeddy.MultiFreqEddyCurrent/StopDetection',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=multifreq__eddy__pb2.OperationReply.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/multifreqeddy.MultiFreqEddyCurrent/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=multifreq__eddy__pb2.RuntimeStatus.FromString,
                _registered_method=True)
        self.GetLatestFrame = channel.unary_unary(
                '/multifreqeddy.MultiFreqEddyCurrent/GetLatestFrame',
                request_serializer=multifreq__eddy__pb2.GetLatestFrameRequest.SerializeToString,
                response_deserializer=multifreq__eddy__pb2.DetectionFrame.FromString,
                _registered_method=True)
        self.StreamFrames = channel.unary_stream(
                '/multifreqeddy.MultiFreqEddyCurrent/StreamFrames',
                request_serializer=multifreq__eddy__pb2.StreamFramesRequest.SerializeToString,
                response_deserializer=multifreq__eddy__pb2.DetectionFrame.FromString,
                _registered_method=True)


class MultiFreqEddyCurrentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MultiFreqEddyCurrentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=multifreq__eddy__pb2.ListDevicesResponse.SerializeToString,
            ),
            'StartDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDetection,
                    request_deserializer=multifreq__eddy__pb2.StartDetectionRequest.FromString,
                    response_serializer=multifreq__eddy__pb2.OperationReply.SerializeToString,
            ),
            'StopDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.StopDetection,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=multifreq__eddy__pb2.OperationReply.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=multifreq__eddy__pb2.RuntimeStatus.SerializeToString,
            ),
            'GetLatestFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestFrame,
                    request_deserializer=multifreq__eddy__pb2.GetLatestFrameRequest.FromString,
                    response_serializer=multifreq__eddy__pb2.DetectionFrame.SerializeToString,
            ),
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=multifreq__eddy__pb2.StreamFramesRequest.FromString,
                    response_serializer=multifreq__eddy__pb2.DetectionFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multifreqeddy.MultiFreqEddyCurrent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('multifreqeddy.MultiFreqEddyCurrent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MultiFreqEddyCurrent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multifreqeddy.MultiFreqEddyCurrent/ListDevices',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            multifreq__eddy__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multifreqeddy.MultiFreqEddyCurrent/StartDetection',
            multifreq__eddy__pb2.StartDetectionRequest.SerializeToString,
            multifreq__eddy__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multifreqeddy.MultiFreqEddyCurrent/StopDetection',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            multifreq__eddy__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multifreqeddy.MultiFreqEddyCurrent/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            multifreq__eddy__pb2.RuntimeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multifreqeddy.MultiFreqEddyCurrent/GetLatestFrame',
            multifreq__eddy__pb2.GetLatestFrameRequest.SerializeToString,
            multifreq__eddy__pb2.DetectionFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/multifreqeddy.MultiFreqEddyCurrent/StreamFrames',
            multifreq__eddy__pb2.StreamFramesRequest.SerializeToString,
            multifreq__eddy__pb2.DetectionFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
