# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import pulse_eddy_pb2 as pulse__eddy__pb2


class PulseEddyStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/pulseeddy.PulseEddy/ListDevices',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pulse__eddy__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.OpenDevice = channel.unary_unary(
                '/pulseeddy.PulseEddy/OpenDevice',
                request_serializer=pulse__eddy__pb2.OpenDeviceRequest.SerializeToString,
                response_deserializer=pulse__eddy__pb2.OperationReply.FromString,
                _registered_method=True)
        self.StartAcquisition = channel.unary_unary(
                '/pulseeddy.PulseEddy/StartAcquisition',
                request_serializer=pulse__eddy__pb2.StartAcquisitionRequest.SerializeToString,
                response_deserializer=pulse__eddy__pb2.OperationReply.FromString,
                _registered_method=True)
        self.StopAcquisition = channel.unary_unary(
                '/pulseeddy.PulseEddy/StopAcquisition',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pulse__eddy__pb2.OperationReply.FromString,
                _registered_method=True)
        self.CloseDevice = channel.unary_unary(
                '/pulseeddy.PulseEddy/CloseDevice',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pulse__eddy__pb2.OperationReply.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/pulseeddy.PulseEddy/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pulse__eddy__pb2.PulseStatus.FromString,
                _registered_method=True)
        self.GetLatestFrame = channel.unary_unary(
                '/pulseeddy.PulseEddy/GetLatestFrame',
                request_serializer=pulse__eddy__pb2.GetLatestFrameRequest.SerializeToString,
                response_deserializer=pulse__eddy__pb2.PulseFrame.FromString,
                _registered_method=True)
        self.StreamFrames = channel.unary_stream(
                '/pulseeddy.PulseEddy/StreamFrames',
                request_serializer=pulse__eddy__pb2.StreamFramesRequest.SerializeToString,
                response_deserializer=pulse__eddy__pb2.PulseFrame.FromString,
                _registered_method=True)
        self.StartReferenceCapture = channel.unary_unary(
                '/pulseeddy.PulseEddy/StartReferenceCapture',
                request_serializer=pulse__eddy__pb2.StartReferenceCaptureRequest.SerializeToString,
                response_deserializer=pulse__eddy__pb2.OperationReply.FromString,
                _registered_method=True)
        self.ClearReference = channel.unary_unary(
                '/pulseeddy.PulseEddy/ClearReference',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=pulse__eddy__pb2.OperationReply.FromString,
                _registered_method=True)


class PulseEddyServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartAcquisition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopAcquisition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLatestFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartReferenceCapture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearReference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PulseEddyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pulse__eddy__pb2.ListDevicesResponse.SerializeToString,
            ),
            'OpenDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenDevice,
                    request_deserializer=pulse__eddy__pb2.OpenDeviceRequest.FromString,
                    response_serializer=pulse__eddy__pb2.OperationReply.SerializeToString,
            ),
            'StartAcquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.StartAcquisition,
                    request_deserializer=pulse__eddy__pb2.StartAcquisitionRequest.FromString,
                    response_serializer=pulse__eddy__pb2.OperationReply.SerializeToString,
            ),
            'StopAcquisition': grpc.unary_unary_rpc_method_handler(
                    servicer.StopAcquisition,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pulse__eddy__pb2.OperationReply.SerializeToString,
            ),
            'CloseDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseDevice,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pulse__eddy__pb2.OperationReply.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pulse__eddy__pb2.PulseStatus.SerializeToString,
            ),
            'GetLatestFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLatestFrame,
                    request_deserializer=pulse__eddy__pb2.GetLatestFrameRequest.FromString,
                    response_serializer=pulse__eddy__pb2.PulseFrame.SerializeToString,
            ),
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=pulse__eddy__pb2.StreamFramesRequest.FromString,
                    response_serializer=pulse__eddy__pb2.PulseFrame.SerializeToString,
            ),
            'StartReferenceCapture': grpc.unary_unary_rpc_method_handler(
                    servicer.StartReferenceCapture,
                    request_deserializer=pulse__eddy__pb2.StartReferenceCaptureRequest.FromString,
                    response_serializer=pulse__eddy__pb2.OperationReply.SerializeToString,
            ),
            'ClearReference': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearReference,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=pulse__eddy__pb2.OperationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pulseeddy.PulseEddy', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pulseeddy.PulseEddy', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PulseEddy(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pulseeddy.PulseEddy/ListDevices',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pulse__eddy__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pulseeddy.PulseEddy/OpenDevice',
            pulse__eddy__pb2.OpenDeviceRequest.SerializeToString,
            pulse__eddy__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartAcquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pulseeddy.PulseEddy/StartAcquisition',
            pulse__eddy__pb2.StartAcquisitionRequest.SerializeToString,
            pulse__eddy__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopAcquisition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pulseeddy.PulseEddy/StopAcquisition',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pulse__eddy__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pulseeddy.PulseEddy/CloseDevice',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pulse__eddy__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pulseeddy.PulseEddy/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pulse__eddy__pb2.PulseStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLatestFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pulseeddy.PulseEddy/GetLatestFrame',
            pulse__eddy__pb2.GetLatestFrameRequest.SerializeToString,
            pulse__eddy__pb2.PulseFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pulseeddy.PulseEddy/StreamFrames',
            pulse__eddy__pb2.StreamFramesRequest.SerializeToString,
            pulse__eddy__pb2.PulseFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartReferenceCapture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pulseeddy.PulseEddy/StartReferenceCapture',
            pulse__eddy__pb2.StartReferenceCaptureRequest.SerializeToString,
            pulse__eddy__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearReference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pulseeddy.PulseEddy/ClearReference',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            pulse__eddy__pb2.OperationReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
