# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import stage_pb2 as stage__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in stage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.unary_unary(
                '/stage.StageService/Connect',
                request_serializer=stage__pb2.ConnectRequest.SerializeToString,
                response_deserializer=stage__pb2.Result.FromString,
                _registered_method=True)
        self.Disconnect = channel.unary_unary(
                '/stage.StageService/Disconnect',
                request_serializer=stage__pb2.Empty.SerializeToString,
                response_deserializer=stage__pb2.Result.FromString,
                _registered_method=True)
        self.GetPositions = channel.unary_unary(
                '/stage.StageService/GetPositions',
                request_serializer=stage__pb2.Empty.SerializeToString,
                response_deserializer=stage__pb2.PositionsReply.FromString,
                _registered_method=True)
        self.PositionStream = channel.unary_stream(
                '/stage.StageService/PositionStream',
                request_serializer=stage__pb2.PositionStreamRequest.SerializeToString,
                response_deserializer=stage__pb2.PositionsReply.FromString,
                _registered_method=True)
        self.Jog = channel.unary_unary(
                '/stage.StageService/Jog',
                request_serializer=stage__pb2.JogRequest.SerializeToString,
                response_deserializer=stage__pb2.Result.FromString,
                _registered_method=True)
        self.MoveAbs = channel.unary_unary(
                '/stage.StageService/MoveAbs',
                request_serializer=stage__pb2.MoveAbsRequest.SerializeToString,
                response_deserializer=stage__pb2.Result.FromString,
                _registered_method=True)
        self.MoveRel = channel.unary_unary(
                '/stage.StageService/MoveRel',
                request_serializer=stage__pb2.MoveRelRequest.SerializeToString,
                response_deserializer=stage__pb2.Result.FromString,
                _registered_method=True)
        self.SetSpeed = channel.unary_unary(
                '/stage.StageService/SetSpeed',
                request_serializer=stage__pb2.SetSpeedRequest.SerializeToString,
                response_deserializer=stage__pb2.Result.FromString,
                _registered_method=True)
        self.StartScan = channel.unary_unary(
                '/stage.StageService/StartScan',
                request_serializer=stage__pb2.ScanRequest.SerializeToString,
                response_deserializer=stage__pb2.Result.FromString,
                _registered_method=True)
        self.StopScan = channel.unary_unary(
                '/stage.StageService/StopScan',
                request_serializer=stage__pb2.Empty.SerializeToString,
                response_deserializer=stage__pb2.Result.FromString,
                _registered_method=True)
        self.GetScanStatus = channel.unary_unary(
                '/stage.StageService/GetScanStatus',
                request_serializer=stage__pb2.Empty.SerializeToString,
                response_deserializer=stage__pb2.ScanStatusReply.FromString,
                _registered_method=True)


class StageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Connect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disconnect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PositionStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Jog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveAbs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveRel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetScanStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.unary_unary_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=stage__pb2.ConnectRequest.FromString,
                    response_serializer=stage__pb2.Result.SerializeToString,
            ),
            'Disconnect': grpc.unary_unary_rpc_method_handler(
                    servicer.Disconnect,
                    request_deserializer=stage__pb2.Empty.FromString,
                    response_serializer=stage__pb2.Result.SerializeToString,
            ),
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=stage__pb2.Empty.FromString,
                    response_serializer=stage__pb2.PositionsReply.SerializeToString,
            ),
            'PositionStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PositionStream,
                    request_deserializer=stage__pb2.PositionStreamRequest.FromString,
                    response_serializer=stage__pb2.PositionsReply.SerializeToString,
            ),
            'Jog': grpc.unary_unary_rpc_method_handler(
                    servicer.Jog,
                    request_deserializer=stage__pb2.JogRequest.FromString,
                    response_serializer=stage__pb2.Result.SerializeToString,
            ),
            'MoveAbs': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveAbs,
                    request_deserializer=stage__pb2.MoveAbsRequest.FromString,
                    response_serializer=stage__pb2.Result.SerializeToString,
            ),
            'MoveRel': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveRel,
                    request_deserializer=stage__pb2.MoveRelRequest.FromString,
                    response_serializer=stage__pb2.Result.SerializeToString,
            ),
            'SetSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSpeed,
                    request_deserializer=stage__pb2.SetSpeedRequest.FromString,
                    response_serializer=stage__pb2.Result.SerializeToString,
            ),
            'StartScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScan,
                    request_deserializer=stage__pb2.ScanRequest.FromString,
                    response_serializer=stage__pb2.Result.SerializeToString,
            ),
            'StopScan': grpc.unary_unary_rpc_method_handler(
                    servicer.StopScan,
                    request_deserializer=stage__pb2.Empty.FromString,
                    response_serializer=stage__pb2.Result.SerializeToString,
            ),
            'GetScanStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetScanStatus,
                    request_deserializer=stage__pb2.Empty.FromString,
                    response_serializer=stage__pb2.ScanStatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'stage.StageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('stage.StageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Connect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/Connect',
            stage__pb2.ConnectRequest.SerializeToString,
            stage__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disconnect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/Disconnect',
            stage__pb2.Empty.SerializeToString,
            stage__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/GetPositions',
            stage__pb2.Empty.SerializeToString,
            stage__pb2.PositionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PositionStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/stage.StageService/PositionStream',
            stage__pb2.PositionStreamRequest.SerializeToString,
            stage__pb2.PositionsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Jog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/Jog',
            stage__pb2.JogRequest.SerializeToString,
            stage__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveAbs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/MoveAbs',
            stage__pb2.MoveAbsRequest.SerializeToString,
            stage__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveRel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/MoveRel',
            stage__pb2.MoveRelRequest.SerializeToString,
            stage__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/SetSpeed',
            stage__pb2.SetSpeedRequest.SerializeToString,
            stage__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/StartScan',
            stage__pb2.ScanRequest.SerializeToString,
            stage__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/StopScan',
            stage__pb2.Empty.SerializeToString,
            stage__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetScanStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/stage.StageService/GetScanStatus',
            stage__pb2.Empty.SerializeToString,
            stage__pb2.ScanStatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
